[package]
name = "noir_bigcurve"
type = "lib"
authors = [""]
compiler_version = ">=0.35.0"

[dependencies]
bignum = {tag = "v0.3.5", git = "https://github.com/noir-lang/noir-bignum"}
# bignum = {tag = "zw/redc_param_fix", git = "https://github.com/noir-lang/noir-bignum"}
# bignum = {path = "../noir-bignum"}
